// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restoration_Project.Models;

namespace Restoration_Project.Migrations
{
    [DbContext(typeof(JosephJeopardyContext))]
    [Migration("20230409033321_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Restoration_Project.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerNum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Corr_Wrong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullAnswer")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Alvin Smith",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 2,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Lucy Smith",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 3,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum Smith",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 4,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "William Smith",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 5,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Equivalent to an elementary level education",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 6,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Equivalent to a middle school level education",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 7,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Equivalent to a high school level education",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 8,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Equivalent to an college level education",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 9,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "John the Baptist",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 10,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Peter, James and John",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 11,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Elijah",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 12,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Jesus Christ",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 13,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Repent",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 14,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Talk to his father",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 15,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Go to the woods",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 16,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Study",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 17,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "THe told him the vision was of the devil",
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 18,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "He gave him a hug and told him he was proud of him",
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 19,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "He kicked him out of his congregation",
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 20,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "He was confused, but continued to listen with respect and curiousity",
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 21,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Emma Smith",
                            QuestionId = 6
                        },
                        new
                        {
                            AnswerId = 22,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Martin Harris",
                            QuestionId = 6
                        },
                        new
                        {
                            AnswerId = 23,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum Smith",
                            QuestionId = 6
                        },
                        new
                        {
                            AnswerId = 24,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Oliver Cowdery",
                            QuestionId = 6
                        },
                        new
                        {
                            AnswerId = 25,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "More, save Jesus only",
                            QuestionId = 7
                        },
                        new
                        {
                            AnswerId = 26,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Restored priesthood keys",
                            QuestionId = 7
                        },
                        new
                        {
                            AnswerId = 27,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Translated the Book of Mormon",
                            QuestionId = 7
                        },
                        new
                        {
                            AnswerId = 28,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Initiated temple work for the dead",
                            QuestionId = 7
                        },
                        new
                        {
                            AnswerId = 29,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "He told him to tell his father about his vision.",
                            QuestionId = 8
                        },
                        new
                        {
                            AnswerId = 30,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "He told him to go and obtain the plates.",
                            QuestionId = 8
                        },
                        new
                        {
                            AnswerId = 31,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "He told Joseph to run home, because his mother had made pie.",
                            QuestionId = 8
                        },
                        new
                        {
                            AnswerId = 32,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "He told him to find Martin Harris to be his scribe.",
                            QuestionId = 8
                        },
                        new
                        {
                            AnswerId = 33,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "He had to overcome his covetousness and his desire for worldly gain.",
                            QuestionId = 9
                        },
                        new
                        {
                            AnswerId = 34,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "He had to wait until he was strong enough to move the rock where the plates were hidden.",
                            QuestionId = 9
                        },
                        new
                        {
                            AnswerId = 35,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "He had to work on the farm to help his family save money.",
                            QuestionId = 9
                        },
                        new
                        {
                            AnswerId = 36,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "He had to stop being mean to his mother and learn to treat her with respect.",
                            QuestionId = 9
                        },
                        new
                        {
                            AnswerId = 37,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Hyrum: 'I'm a dead man'   Joseph: 'O Lord my God'",
                            QuestionId = 10
                        },
                        new
                        {
                            AnswerId = 38,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum: 'Joseph, run!'   Joseph: 'We will be together with God'",
                            QuestionId = 10
                        },
                        new
                        {
                            AnswerId = 39,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum: 'My God, my Savior'   Joseph: 'Lord, save me'",
                            QuestionId = 10
                        },
                        new
                        {
                            AnswerId = 40,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum: 'Please, protect them'   Joseph: 'Til we meet again'",
                            QuestionId = 10
                        },
                        new
                        {
                            AnswerId = 41,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "His friends",
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 42,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "His brothers",
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 43,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "The local preachers",
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 44,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "The old lady accross the street",
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 45,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "He stood and rebuked them.",
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 46,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "He held his peace and said nothing.",
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 47,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "He stood and attacked the men.",
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 48,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "He sqeezed Parley Pratt's hand and prayed for deliverance.",
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 49,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Satan and his numberless host",
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 50,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Moroni when he was burying the plates",
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 51,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Jesus Christ and the Father",
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 52,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "His future family",
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 53,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Morori appeared and took the interpreting tools away from him",
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 54,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "He fainted",
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 55,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Emma told him that the plates would be lost",
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 56,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "He was less stressed with less pages to keep track of",
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 57,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "The cold air that came into the house when the mob took him to be tarred and feathered",
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 58,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "The masacre at the Haun's Mill",
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 59,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "The Lord punishing Joseph for his disobedience",
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 60,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "The lack of attention Joseph gave him because of his calling",
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 61,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Brigham Young",
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 62,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Porter Rockwell",
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 63,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Martin Harris",
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 64,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Sydney Rigdon",
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 65,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "3 months",
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 66,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "5 months",
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 67,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "18 months",
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 68,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "10 months",
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 69,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Martin Harris needed to withdraw himself from the group",
                            QuestionId = 18
                        },
                        new
                        {
                            AnswerId = 70,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "They needed to repent of their sins",
                            QuestionId = 18
                        },
                        new
                        {
                            AnswerId = 71,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Joseph needed to describe the plates to them",
                            QuestionId = 18
                        },
                        new
                        {
                            AnswerId = 72,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Oliver needed to sneeze",
                            QuestionId = 18
                        },
                        new
                        {
                            AnswerId = 73,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Himself and Sydney Rigdon",
                            QuestionId = 19
                        },
                        new
                        {
                            AnswerId = 74,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Joseph Smith Sr",
                            QuestionId = 19
                        },
                        new
                        {
                            AnswerId = 75,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Martin Harris",
                            QuestionId = 19
                        },
                        new
                        {
                            AnswerId = 76,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Future Millenials",
                            QuestionId = 19
                        },
                        new
                        {
                            AnswerId = 77,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "The 'Voice of Innocence' written by Emma Smith",
                            QuestionId = 20
                        },
                        new
                        {
                            AnswerId = 78,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "The apology letter written by Martin Harris",
                            QuestionId = 20
                        },
                        new
                        {
                            AnswerId = 79,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "The 'Danite Manifesto' written by Joseph Knight",
                            QuestionId = 20
                        },
                        new
                        {
                            AnswerId = 80,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "The second-hand account of Joseph's First Vision written by Orson Hyde",
                            QuestionId = 20
                        },
                        new
                        {
                            AnswerId = 81,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Hyrum Smith",
                            QuestionId = 21
                        },
                        new
                        {
                            AnswerId = 82,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Sydney Rigdon",
                            QuestionId = 21
                        },
                        new
                        {
                            AnswerId = 83,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "John Taylor",
                            QuestionId = 21
                        },
                        new
                        {
                            AnswerId = 84,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Joseph Knight",
                            QuestionId = 21
                        },
                        new
                        {
                            AnswerId = 85,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Your Answer",
                            QuestionId = 22
                        },
                        new
                        {
                            AnswerId = 86,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Prof Sweat's Answer",
                            QuestionId = 22
                        },
                        new
                        {
                            AnswerId = 87,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Your neighbor's answer",
                            QuestionId = 22
                        },
                        new
                        {
                            AnswerId = 88,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "The person-behind-you's answer",
                            QuestionId = 22
                        },
                        new
                        {
                            AnswerId = 89,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "A visions of the Plan of Salvation",
                            QuestionId = 23
                        },
                        new
                        {
                            AnswerId = 90,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "God revealing the high priesthood",
                            QuestionId = 23
                        },
                        new
                        {
                            AnswerId = 91,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "A vision of how Joseph would die",
                            QuestionId = 23
                        },
                        new
                        {
                            AnswerId = 92,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Marvel's Vision",
                            QuestionId = 23
                        },
                        new
                        {
                            AnswerId = 93,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "An angel appeared to him with a drawn sword to command him to implement the practice",
                            QuestionId = 24
                        },
                        new
                        {
                            AnswerId = 94,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Emma was so happy that she gave him a big hug and kiss",
                            QuestionId = 24
                        },
                        new
                        {
                            AnswerId = 95,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Emma worked to stop the practice all together",
                            QuestionId = 24
                        },
                        new
                        {
                            AnswerId = 96,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "The power of revelation was taken away from him for a time",
                            QuestionId = 24
                        },
                        new
                        {
                            AnswerId = 97,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Thomas B. Marsh, W.W. Phelps, Orson Hyde, and John Whitmer",
                            QuestionId = 25
                        },
                        new
                        {
                            AnswerId = 98,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Oliver Cowdery, John Whitmer, and Martin Harris",
                            QuestionId = 25
                        },
                        new
                        {
                            AnswerId = 99,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "W.W. Phelps, Oliver Cowdery, Joseph Knight, and John C. Bennett",
                            QuestionId = 25
                        },
                        new
                        {
                            AnswerId = 100,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "John C. Bennett, Francis M. Higbee, and James Foster",
                            QuestionId = 25
                        });
                });

            modelBuilder.Entity("Restoration_Project.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullQuestion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Viewed")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId");

                    b.HasIndex("TopicId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Explanation = "Alvin Smith was described as being 'serious and hardworking, and Joseph loved and admired him immensely.' Joseph looked to Alvin for advice and support and Alvin was happy to give it to him. Being one of the first people who believed Joseph’s accounts of his visions, he encouraged Joseph to do all he could to fulfill the will of God.",
                            FullQuestion = "Which family member was Joseph closest to and looked up to the most?",
                            PointValue = 100,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 2,
                            Explanation = "The Smith family was stricken with poverty and could not afford the luxury of public education. This was not terribly uncommon for families in similar situations during the early 1800s. Though Joseph had very little formal education, he was able to translate an ancient record in a foreign language in just a few months. It seems that the odds were stacked against him. Therefore, this could only have been done through the gift and power of God. And Joseph did not claim to have translated it in any other way.",
                            FullQuestion = "What level of education did Joseph have when he began translating the Book of Mormon?",
                            PointValue = 100,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 3,
                            Explanation = "In his lifetime, John the Baptist had authority and power from God known as the Aaronic Priesthood. This gave him the authority to baptize, the power of the ministering of angels, and more. Therefore, he was chosen to pass this power and authority on to Joseph and Oliver so that the work of salvation could move forward on this earth.",
                            FullQuestion = "Who visited Joseph and Oliver Cowdery to confer the Aaronic Priesthood on them and give them the authority to baptize?",
                            PointValue = 100,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 4,
                            Explanation = "Before Joseph was able to receive any guidance from the Lord, he had to be sufficiently humble. This was the case when he first came to God to find the true church, when Moroni visited him to tell him about the plates, when he went to obtain the plates, and countless other times. Just like us, Joseph too had many things to repent of and much refining to go through. However, once he repented, the Lord’s trust was restored in Joseph, and he was again worthy to further the work.",
                            FullQuestion = "Joseph records that in his early encounters with God and other heavenly beings, he first had to _____ before receiving any further knowledge or instruction.",
                            PointValue = 100,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 5,
                            Explanation = "This preacher along with most other people in the community responded with contempt when Joseph told about his vision. They assumed he was a young boy trying to start trouble, or making himself look good, or confuse people, or that he had been possessed by the devil. None of them would believe that God had spoken to a teenage boy in a poor family. But this was the perfect person for God to speak to. He was humble, he was hungry for knowledge, and he was willing to do what it took to gain that knowledge. But the people refused to see this and mocked Joseph relentlessly for it.",
                            FullQuestion = "How did the local Methodist preacher respond after Joseph told him about his first vision?",
                            PointValue = 100,
                            TopicId = 5,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 6,
                            Explanation = "The angel Moroni originally instructed Joseph to bring Alvin with him to obtain the plates. When Alvin died, Joseph didn't know who he would bring with him. But, Moroni assured him that he would know who he was to bring when the time was right. Throughout their life together, Emma became more than his wife. She also became his companion. They worked together as a team and took care of each other in love. ‘Like Alvin, she was someone who could help him become the man the Lord needed to carry out His work.’ (Saints v.1, p34)",
                            FullQuestion = "When Joseph was finally authorized to obtain the plates, who did he take with him?",
                            PointValue = 200,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 7,
                            Explanation = "D&C 135:3 reads 'Joseph Smith, the Prophet and Seer of the Lord, has done more, save Jesus only, for the salvation of men in this world, than any other man that ever lived in it.' When we think of all the blessings that we as members of the church enjoy, we owe most of the restoration of these blessings to Joseph and the work he did on this earth. He in large part helped make it possible for all men to return to God.",
                            FullQuestion = "What does D&C 135 state that Joseph did for the salvation of men?",
                            PointValue = 200,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 8,
                            Explanation = "Moroni knew that Joseph’s father was a man of faith and that he would believe him when he told him about this vision. Moroni also knew that Joseph’s father could provide him with reassurance, support, and guidance. And that he did. When Joseph told his father about this vision, he began to weep and told Joseph that “It was a vision from God,” and to “Attend to it.”",
                            FullQuestion = "Joseph was working in the field the day after Moroni’s first visit. On his way home, Joseph collapsed due to exhaustion and was again visited by Moroni. In addition to rehearsing what he said the night before, what else did Moroni tell Joseph this time?",
                            PointValue = 200,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 9,
                            Explanation = "Each time that Joseph came in the years before, the Lord knew he wasn't ready to protect the plates and use them only for the sacred purpose the were intended. The 1st time he went to obtain them, he thought of the worldly worth of the plates, was physically shocked, and could not obtain them. The 2nd time, when reaching for the plates, he thought of covering the other items there that might be valueable. He took his eyes off the plates for a second and they disappeared. He was not yet ready to protect the plates. The 3rd time, Joseph had been working as a 'money digger' (similar to a treasure hunter) and Moroni told him to quit this job before he could receive the plates. The fourth year, Joseph had been sufficiently prepared and he could then take the plates.",
                            FullQuestion = "What was the reason Joseph had to wait 4 years before he could obtain the plates?",
                            PointValue = 200,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 10,
                            Explanation = "After an invasion of mob men to their prison room in Carthage Jail, Joseph and Hyrum were both shot bringing their service to the Lord on this earth to an end. Sealing their testimonies with their lives. The two other men in the prison with them, John Taylor and Willard Richards, survived the raid and gave their testimony of the event. It is because of these men's accounts of this day that we know the truthfulness of the events of June 27th, 1844.",
                            FullQuestion = "What were Joseph and Hyrum's final exclamations when they were killed?",
                            PointValue = 200,
                            TopicId = 5,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 11,
                            Explanation = "Like most young people, Joseph and his friends cared a lot about worldly wealth and gain. Accounting this time of his life, Joseph wrote ,’I was left to all kinds of temptations; and, mingling with all kinds of society, I frequently fell into many foolish errors, and displayed the weakness of youth.’ (JSH 1:28) This desire and focus on the vanities of the world would prove to be a hindrance for Joseph in the future in fulfilling the Lord's wishes.",
                            FullQuestion = "Who influenced Joseph as a young man to do foolish things and got him into trouble at times?",
                            PointValue = 300,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 12,
                            Explanation = "Despite the fact that Joseph was a prisoner of those that he rebuked, he had had enough of their cruel speech. Parley P. Pratt, who was a fellow prisoner at this time, recorded Joseph’s rebuke. ‘SILENCE, ye fiends of the infernal pit. In the name of Jesus Christ I rebuke you, and command you to be still; I will not live another minute and hear such language. Cease such talk, or you or I die THIS INSTANT!’ This terrified their captors who then hid and begged for his pardon. However, it encouraged the other prisoners as they saw their leader stand as an angel, steadfast and dignified rebuking these men.",
                            FullQuestion = "While in jail in Richmond, Missouri, Joseph and other church leaders were tied up on the floor listening to their captors mock and speak cruelly against them and their fellow members. What did Joseph do in response to their mockery and filthy language?",
                            PointValue = 300,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 13,
                            Explanation = "Although this vision may seem harsh, this was Moroni’s way of warning Joseph. ‘’Look,’ Moroni commanded. Another vision unfolded before Joseph, and he saw Satan surrounded by his numberless host. ‘All this is shown, the good and the evil, the holy and impure, the glory of God and the power of darkness,’ the angel declared, ‘that you may know hereafter the two powers and never be influenced or overcome by that wicked one.’’ (Saints vol.1, p26) This would prove to be an important lesson for Joseph to learn as Satan would do all he could to stop the work of the Lord.",
                            FullQuestion = "Who did Moroni show to Joseph in a vision the first time he found the plates and was rebuked for trying to take them for gain?",
                            PointValue = 300,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 14,
                            Explanation = "Saints Vol. 1 records that right after Martin left, even before the pages were lost, Moroni appeared to take the interpreting tools away from Joseph. It was of course a tragedy that the pages were lost along with the teachings and story in those pages, but it was more tragic that Joseph had disobeyed God. This was an important lesson for Joseph to learn, but it was also very excruciating time for him, knowing that he had disobeyed and disappointed God.",
                            FullQuestion = "What happened to Joseph after Martin Harris left with the pages of the translated manuscript?",
                            PointValue = 300,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 15,
                            Explanation = "People in the community and some in the church were so mad at Joseph’s claims that he had seen visions and was receiving extra knowledge from God. They banded together to drag Joseph out of his house in the middle of the night and tar and feather his body. This was a heart wrenching experience for Joseph and Emma. And on top of it, their son died about a week later due to the draft from the door opening when the men dragged him away.",
                            FullQuestion = "Julia and Joseph, twin babies of Emma and Joseph, suffered from measles as infants. However, what does Joseph blame for the death of his son (Joseph)?",
                            PointValue = 300,
                            TopicId = 5,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 16,
                            Explanation = "Due to different controversial things President Brigham was involved in, his name is used to revile the Lord’s church.Unfortunately, even some members of the church look to Brigham Young with distaste and disdain.However, without the things that Brigham Young did for the church, all of the work of Joseph might have been lost. People thought that once Joseph was dead, the church would crumble. It is a common practice in history that in order to silence a religious sect, you take out its leader.This was especially evident in England during the Protestant Reformation. But Brigham Young was not going to let that happen. He made sure that the church thrived and continued with the vigor that Joseph had started it with.",
                            FullQuestion = "Moroni told Joseph that his name 'should be had for good and evil among all nations, kindreds, and tongues' (JSH 1:33). Who else did Joseph say this statement applied to?",
                            PointValue = 400,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 17,
                            Explanation = "Joseph and his various scribes experienced a lot of difficulties in trying to translate the Book of Mormon. Because of this, they were forced to hide the plates, translate sporadically, and translate quickly to get it completed and to protect the plates. Although it was about two years from the time Joseph received the plates to when they were finished being translated, the majority of this translation was done from April 1829 to June 1829. As Joseph declared, the only way this was possible, is through the power and gift of God.",
                            FullQuestion = "The majority of the Book of Mormon was translated in the span of how many months?",
                            PointValue = 400,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 18,
                            Explanation = "After Joseph had chosen who the three witnesses were to be, he took them to the woods to pray to God to reveal the plates. They all prayed fervently, but nothing happened. Then Martin expressed that he felt he was the reason they weren’t receiving an answer, and he left their presence. Once he left, the other three were shown the vision of the plates. Once this vision was over, Joseph left Oliver and David and found Martin praying. He joined him and they too were able to see the same vision.",
                            FullQuestion = "What had to happen before Joseph Smith, David Whitmer, Martin Harris, and Oliver Cowdery (the 3 witnesses) were shown the vision of the plates?",
                            PointValue = 400,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 19,
                            Explanation = "This statement in D&C 121:39 was written when Joseph was reflecting on the events of the past months. Many members had apostatized and were now fighting against the church, the Danites and other groups were forcing these people out, Sydney Rigdon had given a speech encouraging such action (the Salt Sermon), and Joseph had lashed out in rage at men that had betrayed him. This verse seems to imply that Joseph was rethinking his own actions and the actions of men he supported (like Sydney) and condeming these actions.",
                            FullQuestion = "In addition to the men that had betrayed Joseph and apostatized from the church, who else might Joseph have been speaking about in D&C 121:39? (look up the verse and think of historical context)",
                            PointValue = 400,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 20,
                            Explanation = "Emma was back and forth about the revelation of plural marriage most of her life. In a time when she was contemptuous of it, Emma saw an opportunity to fight against plural marriage. She used her station as president of the Relief Society to convince many women to sign a document saying the practice was adulterous. But this document only gave the enemies of Joseph (who were already mad about the practice of polygamy) fuel. Joseph Smith wrote, ‘I never had any fuss with these men until that Female Relief Society brought out the paper against adulterers and adulteresses.’",
                            FullQuestion = "What document did Joseph blame for the resistance of the men who led the mod that eventually killed him? And who wrote/commissioned this document?",
                            PointValue = 400,
                            TopicId = 5,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 21,
                            Explanation = "Hyrum stayed by Joseph’s side. He was promised by the Lord that he would not be killed unless he chose to allow himself to die. When he rode off to Carthage with Joseph, Joseph told him to stay because he knew they would likely be killed. But Hyrum decided to go with him, sealing his testimony with his life that he chose to give up.",
                            FullQuestion = "Joseph had a loyal friend who was given the promise that his life would only be taken away from him if he chose. This friend chose to give us his life for the church. Who was his friend?",
                            PointValue = 500,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 22,
                            Explanation = "There is much we can learn from the life of Joseph Smith and much of his life that we can consider miracles. This could be the translation of the Book of Mormon, the times when his life was spared, a miracle of healing he performed, the miracle of the repentance of Joseph Smith, and more. Which is most impactful to you?",
                            FullQuestion = "Application Question: Which miracle of Joseph’s Smith life is most meaningful to you?",
                            PointValue = 500,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 23,
                            Explanation = "Earlier, Joseph and Sydney had been contemplating the idea that God is so gracious to us on this earth to give us so many chances, why is it not like that in heaven? In this vision, they saw the three degrees of glory in the heavens, confirming their suspicions regarding God’s mercy. After the vision had finished, Sydney looked exhausted and pale and Joseph looked to him, smiled, and said ‘Sidney is not used to it as I am.’",
                            FullQuestion = "What vision did Sydney and Joseph have in the upstairs room of the Johnson house in 1832?",
                            PointValue = 500,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 24,
                            Explanation = "Joseph could see the hurt that could be caused by the practice of plural marriage, so he was hesitant to continue to follow and implement the revelation. And he was right, this was a hard revelation for many people at that time and even now. However, the Lord knew all the good that would come out of it. His purposes were higher and He knew what needed to be done in order to fulfill His plan of happiness. Therefore, when Joseph showed resistance, the Lord was stern with him to make sure he carried out this revelation.",
                            FullQuestion = "According to the many second-hand accounts, what happened to Joseph when he hesitated to implement the revelation of plural marriage?",
                            PointValue = 500,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 25,
                            Explanation = "This betrayal left Joseph furious. While in prison, he wrote a letter comparing these men to wicked men in the Bible and saying there were “too mean to mention and we had liked to have forgotten them”. And “whose hearts are full of corruption, whose cloak of hypocrisy was not sufficient to shield them or to hold them up in the hour of trouble”. These were men that he had put his full faith and trust in at one point, whom he once called friends. But, the adversary had gotten hold of their hearts and they no longer cared about the work of Lord.",
                            FullQuestion = "Who were the men who testified against Joseph after he was arrested for treason due to the battles between members and state men in Missouri?",
                            PointValue = 500,
                            TopicId = 5,
                            Viewed = false
                        });
                });

            modelBuilder.Entity("Restoration_Project.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BGColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("DivColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicName")
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId");

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            BGColor = "orangered",
                            DivColor = "peachpuff",
                            TopicName = "People's Influence"
                        },
                        new
                        {
                            TopicId = 2,
                            BGColor = "orange",
                            DivColor = "lightseagreen",
                            TopicName = "A Man of Miracles"
                        },
                        new
                        {
                            TopicId = 3,
                            BGColor = "peachpuff",
                            DivColor = "mediumblue",
                            TopicName = "Visions & Visitations"
                        },
                        new
                        {
                            TopicId = 4,
                            BGColor = "lightseagreen",
                            DivColor = "orangered",
                            TopicName = "Joseph's Fallacies"
                        },
                        new
                        {
                            TopicId = 5,
                            BGColor = "mediumblue",
                            DivColor = "orange",
                            TopicName = "Trial By Fire"
                        });
                });

            modelBuilder.Entity("Restoration_Project.Models.Answer", b =>
                {
                    b.HasOne("Restoration_Project.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restoration_Project.Models.Question", b =>
                {
                    b.HasOne("Restoration_Project.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
