// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restoration_Project.Models;

namespace Restoration_Project.Migrations
{
    [DbContext(typeof(JosephJeopardyContext))]
    partial class JosephJeopardyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Restoration_Project.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerNum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Corr_Wrong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullAnswer")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Alvin Smith",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 2,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Lucy Smith",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 3,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum Smith",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 4,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "William Smith",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 5,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T2 100 Q2 1",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 6,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T2 100 Q2 2",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 7,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T2 100 Q2 3",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 8,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T2 100 Q2 4",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 9,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T3 100 Q3 1",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 10,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T3 100 Q3 2",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 11,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T3 100 Q3 3",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 12,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T3 100 Q3 4",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 13,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T4 100 Q4 1",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 14,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T4 100 Q4 2",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 15,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T4 100 Q4 3",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 16,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T4 100 Q4 4",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 17,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T5 100 Q5 1",
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 18,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T5 100 Q5 2",
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 19,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T5 100 Q5 3",
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 20,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T5 100 Q5 4",
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 21,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Emma Smith",
                            QuestionId = 6
                        },
                        new
                        {
                            AnswerId = 22,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Martin Harris",
                            QuestionId = 6
                        },
                        new
                        {
                            AnswerId = 23,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum Smith",
                            QuestionId = 6
                        },
                        new
                        {
                            AnswerId = 24,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Oliver Cowdery",
                            QuestionId = 6
                        },
                        new
                        {
                            AnswerId = 25,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "More, save Jesus only",
                            QuestionId = 7
                        },
                        new
                        {
                            AnswerId = 26,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Restored priesthood keys",
                            QuestionId = 7
                        },
                        new
                        {
                            AnswerId = 27,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Translated the Book of Mormon",
                            QuestionId = 7
                        },
                        new
                        {
                            AnswerId = 28,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Initiated temple work for the dead",
                            QuestionId = 7
                        },
                        new
                        {
                            AnswerId = 29,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "He told him to tell his father about his vision.",
                            QuestionId = 8
                        },
                        new
                        {
                            AnswerId = 30,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "He told him to go and obtain the plates.",
                            QuestionId = 8
                        },
                        new
                        {
                            AnswerId = 31,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "He told Joseph to run home, because his mother had made pie.",
                            QuestionId = 8
                        },
                        new
                        {
                            AnswerId = 32,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "He told him to find Martin Harris to be his scribe.",
                            QuestionId = 8
                        },
                        new
                        {
                            AnswerId = 33,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "He had to overcome his covetousness and his desire for worldly gain.",
                            QuestionId = 9
                        },
                        new
                        {
                            AnswerId = 34,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "He had to wait until he was strong enough to move the rock where the plates were hidden.",
                            QuestionId = 9
                        },
                        new
                        {
                            AnswerId = 35,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "He had to work on the farm to help his family save money.",
                            QuestionId = 9
                        },
                        new
                        {
                            AnswerId = 36,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "He had to stop being mean to his mother and learn to treat her with respect.",
                            QuestionId = 9
                        },
                        new
                        {
                            AnswerId = 37,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Hyrum: 'I'm a dead man'   Joseph: 'O Lord my God'",
                            QuestionId = 10
                        },
                        new
                        {
                            AnswerId = 38,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum: 'Joseph, run!'   Joseph: 'We will be together with God'",
                            QuestionId = 10
                        },
                        new
                        {
                            AnswerId = 39,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum: 'My God, my Savior'   Joseph: 'Lord, save me'",
                            QuestionId = 10
                        },
                        new
                        {
                            AnswerId = 40,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Hyrum: 'Please, protect them'   Joseph: 'Til we meet again'",
                            QuestionId = 10
                        },
                        new
                        {
                            AnswerId = 41,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "His friends",
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 42,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "His brothers",
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 43,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "The local preachers",
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 44,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "The old lady accross the street",
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 45,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T2 300 Q12 1",
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 46,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T2 300 Q12 2",
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 47,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T2 300 Q12 3",
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 48,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T2 300 Q12 4",
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 49,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T3 300 Q13 1",
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 50,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T3 300 Q13 2",
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 51,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T3 300 Q13 3",
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 52,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T3 300 Q13 4",
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 53,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T4 300 Q14 1",
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 54,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T4 300 Q14 2",
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 55,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T4 300 Q14 3",
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 56,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T4 300 Q14 4",
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 57,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T5 300 Q15 1",
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 58,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T5 300 Q15 2",
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 59,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T5 300 Q15 3",
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 60,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T5 300 Q15 4",
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 61,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "Brigham Young",
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 62,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "Porter Rockwell",
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 63,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "Martin Harris",
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 64,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "Sydney Rigdon",
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 65,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T2 400 Q17 1",
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 66,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T2 400 Q17 2",
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 67,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T2 400 Q17 3",
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 68,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T2 400 Q17 4",
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 69,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T3 400 Q18 1",
                            QuestionId = 18
                        },
                        new
                        {
                            AnswerId = 70,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T3 400 Q18 2",
                            QuestionId = 18
                        },
                        new
                        {
                            AnswerId = 71,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T3 400 Q18 3",
                            QuestionId = 18
                        },
                        new
                        {
                            AnswerId = 72,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T3 400 Q18 4",
                            QuestionId = 18
                        },
                        new
                        {
                            AnswerId = 73,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T4 400 Q19 1",
                            QuestionId = 19
                        },
                        new
                        {
                            AnswerId = 74,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T4 400 Q19 2",
                            QuestionId = 19
                        },
                        new
                        {
                            AnswerId = 75,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T4 400 Q19 3",
                            QuestionId = 19
                        },
                        new
                        {
                            AnswerId = 76,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T4 400 Q19 4",
                            QuestionId = 19
                        },
                        new
                        {
                            AnswerId = 77,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T5 400 Q20 1",
                            QuestionId = 20
                        },
                        new
                        {
                            AnswerId = 78,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T5 400 Q20 2",
                            QuestionId = 20
                        },
                        new
                        {
                            AnswerId = 79,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T5 400 Q20 3",
                            QuestionId = 20
                        },
                        new
                        {
                            AnswerId = 80,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T5 400 Q20 4",
                            QuestionId = 20
                        },
                        new
                        {
                            AnswerId = 81,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T1 500 Q21 1",
                            QuestionId = 21
                        },
                        new
                        {
                            AnswerId = 82,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T1 500 Q21 2",
                            QuestionId = 21
                        },
                        new
                        {
                            AnswerId = 83,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T1 500 Q21 3",
                            QuestionId = 21
                        },
                        new
                        {
                            AnswerId = 84,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T1 500 Q21 4",
                            QuestionId = 21
                        },
                        new
                        {
                            AnswerId = 85,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T2 500 Q22 1",
                            QuestionId = 22
                        },
                        new
                        {
                            AnswerId = 86,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T2 500 Q22 2",
                            QuestionId = 22
                        },
                        new
                        {
                            AnswerId = 87,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T2 500 Q22 3",
                            QuestionId = 22
                        },
                        new
                        {
                            AnswerId = 88,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T2 500 Q22 4",
                            QuestionId = 22
                        },
                        new
                        {
                            AnswerId = 89,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T3 500 Q23 1",
                            QuestionId = 23
                        },
                        new
                        {
                            AnswerId = 90,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T3 500 Q23 2",
                            QuestionId = 23
                        },
                        new
                        {
                            AnswerId = 91,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T3 500 Q23 3",
                            QuestionId = 23
                        },
                        new
                        {
                            AnswerId = 92,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T3 500 Q23 4",
                            QuestionId = 23
                        },
                        new
                        {
                            AnswerId = 93,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T4 500 Q24 1",
                            QuestionId = 24
                        },
                        new
                        {
                            AnswerId = 94,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T4 500 Q24 2",
                            QuestionId = 24
                        },
                        new
                        {
                            AnswerId = 95,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T4 500 Q24 3",
                            QuestionId = 24
                        },
                        new
                        {
                            AnswerId = 96,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T4 500 Q24 4",
                            QuestionId = 24
                        },
                        new
                        {
                            AnswerId = 97,
                            AnswerNum = 1,
                            Corr_Wrong = true,
                            FullAnswer = "T5 500 Q25 1",
                            QuestionId = 25
                        },
                        new
                        {
                            AnswerId = 98,
                            AnswerNum = 2,
                            Corr_Wrong = false,
                            FullAnswer = "T5 500 Q25 2",
                            QuestionId = 25
                        },
                        new
                        {
                            AnswerId = 99,
                            AnswerNum = 3,
                            Corr_Wrong = false,
                            FullAnswer = "T5 500 Q25 3",
                            QuestionId = 25
                        },
                        new
                        {
                            AnswerId = 100,
                            AnswerNum = 4,
                            Corr_Wrong = false,
                            FullAnswer = "T5 500 Q25 4",
                            QuestionId = 25
                        });
                });

            modelBuilder.Entity("Restoration_Project.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullQuestion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Viewed")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId");

                    b.HasIndex("TopicId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Explanation = "Alvin was described as being 'serious and hardworking, and Joseph loved and admired him immensely.' Alvin was one of the first people to believe Joseph about the visions he had been having and he encouraged Joseph to do all he could to fulfill the will of God.",
                            FullQuestion = "Which family member was Joseph closest to and looked up to the most?",
                            PointValue = 100,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 2,
                            Explanation = "Question 2",
                            FullQuestion = "T2 100",
                            PointValue = 100,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 3,
                            Explanation = "Question 3",
                            FullQuestion = "T3 100",
                            PointValue = 100,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 4,
                            Explanation = "Question 4",
                            FullQuestion = " T4 100",
                            PointValue = 100,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 5,
                            Explanation = "Question 5",
                            FullQuestion = "T5 100",
                            PointValue = 100,
                            TopicId = 5,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 6,
                            Explanation = "The angel Moroni originally instructed Joseph to bring Alvin with him to obtain the plates. When Alvin dies, Joseph didn't know who he would bring with him. But, Moroni assured him that he would know who he was to bring when the time was right. Emma became more than his wife, she also became his companion. They worked together as a team and took care of each other in love.",
                            FullQuestion = "When Joseph was finally authorized to obtain the plates, who did he take with him?",
                            PointValue = 200,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 7,
                            Explanation = "D&C 135:3 states 'Joseph Smith, the Prophet and Seer of the Lord, has done more, save Jesus only, for the salvation of men in this world, than any other man that ever lived in it.' When we think of all the blessings that we as members of the church enjoy, we owe most of the restoation of these blessings to Joseph and the work he did on this earth. He helped in the work to make it possible for all men, not only those who are members in this life, to return to God.",
                            FullQuestion = "What does D&C 135 state that Joseph did for the salvation of men?",
                            PointValue = 200,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 8,
                            Explanation = "Moroni visited him",
                            FullQuestion = "Joseph was working in the field the day after Moroni’s first visit. On his way home, Joseph collapsed due to exhaustion and was again visited by Moroni. In addition to rehearsing what he said the night before, what else did Moroni tell Joseph this time?",
                            PointValue = 200,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 9,
                            Explanation = "Each time that Joseph came in the years before, the Lord knew he wasn't ready to protect the plates and use them only for the sacred purpose the were intended. The 1st time he went to obtain them, he thought of the worldly worth of the plates, was physically shocked, and could not obtain them. The 2nd time, when reaching for the plates, he thought of covering the other items there that might be valueable. He took his eyes off the plates for a second and they disappeared. He was not yet ready to protect the plates. The 3rd time, Joseph had been working as a 'money digger' (similar to a treasure hunter) and Moroni told him to quit this job before he could receive the plates. The fourth year, Joseph had been sufficiently prepared and he could then take the plates. ",
                            FullQuestion = "What was the reason Joseph had to wait 4 years before he could obtain the plates?",
                            PointValue = 200,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 10,
                            Explanation = "After an invasion of mob men to their prison room in Carthage Jail, Joseph and Hyrum were both shot bringing their service to the Lord on this earth to an end. Sealing their testimonies with their lives. The two other men in the prison with them, John Taylor and Willard Richards, survived the raid and gave their testimony of the event. It is because of these men's accounts of this day that we know the truthfulness of the events of June 27th, 1844.",
                            FullQuestion = "What were Joseph and Hyrum's final exclamations when they were killed?",
                            PointValue = 200,
                            TopicId = 5,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 11,
                            Explanation = "Like most young people, Joseph and his friends cared a lot about worldly wealth and in particular, treasure. They would often search for it together. This desire and focus on getting gain would be a problem for Joseph in the future in fulfilling the Lord's wishes.",
                            FullQuestion = "Who influenced Joseph as a young man to do foolish things and got him into trouble at times?",
                            PointValue = 300,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 12,
                            Explanation = "Question 12",
                            FullQuestion = "T2 300",
                            PointValue = 300,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 13,
                            Explanation = "Question 13",
                            FullQuestion = "T3 300",
                            PointValue = 300,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 14,
                            Explanation = "Question 14",
                            FullQuestion = " T4 300",
                            PointValue = 300,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 15,
                            Explanation = "Question 15",
                            FullQuestion = "T5 300",
                            PointValue = 300,
                            TopicId = 5,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 16,
                            Explanation = "People thought that once Joseph was dead, the church would crumble. But thanks to Brigham Young, this was not the case. He made sure that the church thrived and continued with the vigor that Joseph had started it with. Unfortunately, people today, even some members of the church, look to President Young with distaste and distain due to things he did that some perceive as sinful. However, without the work that Brigham Young did for the church, all of the work of Joseph might have been lost. President Young was able to keep the fire of the church burning and we have much to thank him for.",
                            FullQuestion = "Moroni told Joseph that his name 'should be had for good and evil among all nations, kindreds, and tongues' (JSH 1:33). Who else did Joseph say this prophecy applied to?",
                            PointValue = 400,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 17,
                            Explanation = "Question 17",
                            FullQuestion = "T2 400",
                            PointValue = 400,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 18,
                            Explanation = "Question 18",
                            FullQuestion = "T3 400",
                            PointValue = 400,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 19,
                            Explanation = "Question 19",
                            FullQuestion = "T4 400",
                            PointValue = 400,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 20,
                            Explanation = "Question 20",
                            FullQuestion = "T5 400",
                            PointValue = 400,
                            TopicId = 5,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 21,
                            Explanation = "Question 21",
                            FullQuestion = "T1 500",
                            PointValue = 500,
                            TopicId = 1,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 22,
                            Explanation = "Question 22",
                            FullQuestion = "T2 500",
                            PointValue = 500,
                            TopicId = 2,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 23,
                            Explanation = "Question 23",
                            FullQuestion = "T3 500",
                            PointValue = 500,
                            TopicId = 3,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 24,
                            Explanation = "Question 24",
                            FullQuestion = " T4 500",
                            PointValue = 500,
                            TopicId = 4,
                            Viewed = false
                        },
                        new
                        {
                            QuestionId = 25,
                            Explanation = "Question 25",
                            FullQuestion = "T5 500",
                            PointValue = 500,
                            TopicId = 5,
                            Viewed = false
                        });
                });

            modelBuilder.Entity("Restoration_Project.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BGColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("DivColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicName")
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId");

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            BGColor = "orangered",
                            DivColor = "peachpuff",
                            TopicName = "People's Influence"
                        },
                        new
                        {
                            TopicId = 2,
                            BGColor = "orange",
                            DivColor = "lightseagreen",
                            TopicName = "A Man of Miracles"
                        },
                        new
                        {
                            TopicId = 3,
                            BGColor = "peachpuff",
                            DivColor = "mediumblue",
                            TopicName = "Visions & Visitations"
                        },
                        new
                        {
                            TopicId = 4,
                            BGColor = "lightseagreen",
                            DivColor = "orangered",
                            TopicName = "Joseph's Falacies"
                        },
                        new
                        {
                            TopicId = 5,
                            BGColor = "mediumblue",
                            DivColor = "orange",
                            TopicName = "Trial By Fire"
                        });
                });

            modelBuilder.Entity("Restoration_Project.Models.Answer", b =>
                {
                    b.HasOne("Restoration_Project.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restoration_Project.Models.Question", b =>
                {
                    b.HasOne("Restoration_Project.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
